package webread

import (
	"fmt"
	"strings"

	"github.com/KoukeNeko/moodle-cli/internal/errs"
)

// Anchors this parser depends on.
//
// They are listed because a page that no longer carries them is a page this
// build cannot read, and saying so is the only honest answer. Each is
// generated by Moodle from data rather than written for a reader, so none of
// them changes with the site's language.
const (
	// anchorStatusTable wraps the submission status table.
	anchorStatusTable = "submissionstatustable"
	// prefixStatus carries the raw submission status, as in
	// "submissionstatusdraft". Moodle builds the token from the database value
	// and translates only the words beside it.
	prefixStatus = "submissionstatus"
	// classGraded and classNotGraded mark the grading status cell.
	classGraded    = "submissiongraded"
	classNotGraded = "submissionnotgraded"
	// classLocked marks a submission Moodle will not accept changes to.
	classLocked = "submissionlocked"
)

// knownStatuses are the submission states Moodle writes into the class.
//
// The list is closed on purpose. Moodle's class names share prefixes, so
// accepting whatever follows "submissionstatus" would read the container's own
// "submissionstatustable" as a status of "table". An unrecognised token is
// left alone rather than reported as a state the caller might act on.
var knownStatuses = map[string]bool{
	"new": true, "draft": true, "submitted": true, "reopened": true,
}

// AssignStatus is what an assignment page says about the caller's submission.
type AssignStatus struct {
	// Status is Moodle's own word: new, draft, submitted or reopened. It is
	// read from a class token, so it matches what the web service API reports
	// for the same submission.
	Status string
	// Graded reports whether the work has been marked.
	Graded bool
	// Locked reports that Moodle will not accept changes.
	Locked bool
	// Files are the names of the submitted files, where the page lists them.
	Files []string
}

// ParseAssignStatus reads mod/assign/view.php.
//
// The status comes from a class Moodle generates from the database value.
// Its absence is meaningful rather than a gap: Moodle omits the class in
// exactly one case, when there is no submission to describe, so an anchored
// table with no status token means nothing has been submitted.
func ParseAssignStatus(markup string) (AssignStatus, error) {
	document, err := parse(markup)
	if err != nil {
		return AssignStatus{}, errs.Wrap(errs.CodeUpstream, err,
			"cannot read the assignment page").
			WithReason(errs.ReasonProtocolDrift)
	}

	table, ok := document.find(byClass(anchorStatusTable))
	if !ok {
		// Without the anchor there is nothing to read, and guessing from
		// whatever else is on the page is how a scraper reports a confident
		// wrong answer.
		return AssignStatus{}, errs.New(errs.CodeUpstream,
			fmt.Sprintf("this assignment page carries no %q section", anchorStatusTable)).
			WithReason(errs.ReasonProtocolDrift).
			WithHint("the site's pages may have changed shape, or this may not be an assignment page")
	}

	status := AssignStatus{Status: "new"}
	for _, cell := range table.findAll(byTag("td")) {
		if token := cell.classWithPrefix(prefixStatus); knownStatuses[token] {
			status.Status = token
		}
		if cell.hasClass(classGraded) {
			status.Graded = true
		}
		if cell.hasClass(classLocked) {
			status.Locked = true
		}
	}
	status.Files = submittedFiles(table)
	return status, nil
}

// submittedFiles reads the names of the files attached to the submission.
//
// Moodle renders them as links into the plugin file area, which is the one
// part of the path that is stable; the link text is the filename the student
// chose and may be anything.
func submittedFiles(table node) []string {
	var files []string
	seen := map[string]bool{}
	for _, link := range table.findAll(byTag("a")) {
		href := link.attr("href")
		if !strings.Contains(href, "/pluginfile.php/") ||
			!strings.Contains(href, "assignsubmission_file") {
			continue
		}
		name := strings.TrimSpace(link.text())
		if name == "" || seen[name] {
			continue
		}
		seen[name] = true
		files = append(files, name)
	}
	return files
}
