package webread

import (
	"fmt"
	"strings"

	"github.com/KoukeNeko/moodle-cli/internal/errs"
)

// Anchors this parser depends on.
//
// They are listed because a page that no longer carries them is a page this
// build cannot read, and saying so is the only honest answer. Each is
// generated by Moodle from data rather than written for a reader, so none of
// them changes with the site's language.
const (
	// anchorStatusTable wraps the submission status table.
	anchorStatusTable = "submissionstatustable"
	// prefixStatus carries the raw submission status, as in
	// "submissionstatusdraft". Moodle builds the token from the database value
	// and translates only the words beside it.
	prefixStatus = "submissionstatus"
	// classGraded and classNotGraded mark the grading status cell.
	classGraded    = "submissiongraded"
	classNotGraded = "submissionnotgraded"
	// classLocked marks a submission Moodle will not accept changes to.
	classLocked = "submissionlocked"
)

// knownStatuses are the submission states Moodle writes into the class.
//
// The list is closed on purpose. Moodle's class names share prefixes, so
// accepting whatever follows "submissionstatus" would read the container's own
// "submissionstatustable" as a status of "table". An unrecognised token is
// left alone rather than reported as a state the caller might act on.
var knownStatuses = map[string]bool{
	"new": true, "draft": true, "submitted": true, "reopened": true,
}

// AssignStatus is what an assignment page says about the caller's submission.
type AssignStatus struct {
	// Status is Moodle's own word: new, draft, submitted or reopened. It is
	// read from a class token, so it matches what the web service API reports
	// for the same submission.
	Status string
	// Graded reports whether the work has been marked.
	Graded bool
	// Locked reports that Moodle will not accept changes.
	Locked bool
	// Files are the submitted files, where the page lists them.
	Files []FileLink
}

// FileLink is a file a page links to.
type FileLink struct {
	Name string
	// URL is the page's own link into pluginfile.php, which a browser session
	// can download.
	URL string
}

// ParseAssignStatus reads mod/assign/view.php.
//
// The status comes from a class Moodle generates from the database value.
// Its absence is meaningful rather than a gap: Moodle omits the class in
// exactly one case, when there is no submission to describe, so an anchored
// table with no status token means nothing has been submitted.
func ParseAssignStatus(markup string) (AssignStatus, error) {
	document, err := parse(markup)
	if err != nil {
		return AssignStatus{}, errs.Wrap(errs.CodeUpstream, err,
			"cannot read the assignment page").
			WithReason(errs.ReasonProtocolDrift)
	}

	table, ok := document.find(byClass(anchorStatusTable))
	if !ok {
		// Without the anchor there is nothing to read, and guessing from
		// whatever else is on the page is how a scraper reports a confident
		// wrong answer.
		return AssignStatus{}, errs.New(errs.CodeUpstream,
			fmt.Sprintf("this assignment page carries no %q section", anchorStatusTable)).
			WithReason(errs.ReasonProtocolDrift).
			WithHint("the site's pages may have changed shape, or this may not be an assignment page")
	}

	status := AssignStatus{Status: "new"}
	for _, cell := range table.findAll(byTag("td")) {
		if token := cell.classWithPrefix(prefixStatus); knownStatuses[token] {
			status.Status = token
		}
		if cell.hasClass(classGraded) {
			status.Graded = true
		}
		if cell.hasClass(classLocked) {
			status.Locked = true
		}
	}
	status.Files = submittedFiles(table)
	return status, nil
}

// submittedFiles reads the files attached to the submission.
//
// Moodle renders them as links into the plugin file area, which is the one
// part of the path that is stable; the link text is the filename the student
// chose and may be anything.
func submittedFiles(table node) []FileLink {
	return fileLinks(table, "assignsubmission_file")
}

// fileLinks reads the links into one file area under a node.
func fileLinks(under node, area string) []FileLink {
	var files []FileLink
	seen := map[string]bool{}
	for _, link := range under.findAll(byTag("a")) {
		href := link.attr("href")
		if !strings.Contains(href, "/pluginfile.php/") || !strings.Contains(href, area) {
			continue
		}
		name := strings.TrimSpace(link.text())
		if name == "" || seen[href] {
			continue
		}
		seen[href] = true
		files = append(files, FileLink{Name: name, URL: href})
	}
	return files
}

// Anchors for the assignment itself.
const (
	// attrActivityName carries the activity's name on its information block.
	// Moodle writes it from the database for scripts to read, so it holds
	// whatever the theme does with the visible heading.
	attrActivityName = "data-activityname"
	// prefixCourse is the body class naming the course, as in "course-36728".
	prefixCourse = "course-"
	// idIntro wraps the description and the teacher's attachments.
	idIntro = "intro"
	// classNoOverflow wraps the description's own markup inside the intro.
	classNoOverflow = "no-overflow"
	// areaIntroAttachment is the file area of the teacher's attachments.
	areaIntroAttachment = "mod_assign/introattachment"
)

// AssignPage is what an assignment page says about the assignment itself.
//
// The dates are on the page too, but only as prose the site formatted in its
// own language; they are left to the calendar, which states them as numbers.
type AssignPage struct {
	// Name is empty when the page does not carry the attribute.
	Name string
	// CourseID is empty when the body carries no course class.
	CourseID string
	// Description is the description's markup, unchanged. Empty both for an
	// assignment without one and for a page that hides it from students
	// until the assignment opens.
	Description string
	Attachments []FileLink
}

// ParseAssignPage reads the assignment's own details off mod/assign/view.php.
func ParseAssignPage(markup string) (AssignPage, error) {
	document, err := parse(markup)
	if err != nil {
		return AssignPage{}, errs.Wrap(errs.CodeUpstream, err,
			"cannot read the assignment page").
			WithReason(errs.ReasonProtocolDrift)
	}

	var page AssignPage
	if info, ok := document.find(func(n node) bool { return n.attr(attrActivityName) != "" }); ok {
		page.Name = strings.TrimSpace(info.attr(attrActivityName))
	}
	if body, ok := document.find(byTag("body")); ok {
		if id := body.classWithPrefix(prefixCourse); isDigits(id) {
			page.CourseID = id
		}
	}
	if intro, ok := document.find(byID(idIntro)); ok {
		if content, ok := intro.find(byClass(classNoOverflow)); ok {
			page.Description = content.innerHTML()
		}
		page.Attachments = fileLinks(intro, areaIntroAttachment)
	}
	return page, nil
}

func isDigits(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}
